### ISSUE TITLE
404 Error for video

### ISSUE THREAD

**Issue by munyari** [ml4a/ml4a.github.io#11]
https://ml4a.github.io/ml4a/machine-learning throws two 404 errors for missing videos (https://ml4a.github.io/images/video.mp4 and https://ml4a.github.io/images/video.webm). This video is the one to illustrate linear classifiers in 3 dimensions (I'm guessing)

**Comment by genekogan** [comment]
this is a draft chapter, so it's not ready yet. these will be fixed in a few months. thanks!
