### ISSUE TITLE
working '_chapters_ko/neural_networks.md'

### ISSUE THREAD

**Issue by rickiepark** [ml4a/ml4a.github.io#18]
I started to translate _chapters_ko/neural_networks.md
If somebody already work in _chapters_ko folder, let me know about it.
Thanks. :)

**Comment by genekogan** [comment]
hi @rickiepark, thanks for doing this!  please note, the english version inside _chapters_ko is outdated, please work off the main one in the folder _chapters! i will connect you to Nahee, who started working on this a few months ago to see if you might be able to coordinate with her.

please note, do not translate the following, leave them as english:

1) the header at the top.
2) don't translate any of the special jekyll statements, which are seen in between "{%" and "%}", for example: {% include neurons.html %}
3) don't translate any of the math equations, which are seen between "$$" and "$$" characters, for example, line 38 starting "$$\begin{eqnarray}"...
4) don't translate URLs!  that should be obvious :)

when you are ready, feel free to submit pull request. you can do it at the end or you can do it in segments, as you wish.

i use a lot of idiomatic english (probably especially american) so if you are not sure of something, please do e-mail me your questions, or you can make notes in the translation to review some statements later and i can help you with them (or you can put them here). i know it's impossible to translate everything from english to korean, so feel free to be creative and change things in the way you think would be best for korean language :)

**Comment by rickiepark** [comment]
Hi, @genekogan 
Thanks for comment. With this guide, I'll make pull-requests several times until finishing this issue. :)

**Comment by rickiepark** [comment]
If there is Wikipedia korean page corresponding to a link, what about changing to the link?
e.g. https://en.wikipedia.org/wiki/Alan_Turing --> https://ko.wikipedia.org/wiki/%EC%95%A8%EB%9F%B0_%ED%8A%9C%EB%A7%81

**Comment by genekogan** [comment]
yes! good idea!

**Comment by rickiepark** [comment]
I close this issue. If there is something to correct in /ko/neural_networks.md, let me know about it. :)
