### ISSUE TITLE
What does the translation workflow look like?

### ISSUE THREAD

**Issue by HerrBertling** [ml4a/ml4a.github.io#29]
Hey @genekogan 👋

After working with this, I thought it would be useful to add german translations since they are still missing. Is there some kind of workflow on how to do this?

I thought of throwing the chapters into https://www.deepl.com/translator and then proof-read the result. I mean… the translation for this should be done with the help of machine learning, right? 😄

**Comment by genekogan** [comment]
would be great to have a German translation!
haven't seen deepl yet... how does it compare to google translate?
i think for technical subjects, ML translations usually come out sounding a bit funny still. but certainly i think any translator is free to use any strategy that works for them.  right now the workflow is really simple -- just copy the english chapter into a new folder (we can make `_chapters_de`) and then just translate the english into german.
there are no guidelines really, translator is free to translate very strict to the original text or can get more creative and modify parts of it. especially where things don't easily translate (for example, there's a lot of english/american idioms that don't always work well translated).
let me know if you'd like to give the neural nets chapter a try (or any of the others)!

**Comment by HerrBertling** [comment]
The rather advertise-y quote underneath the translator pretty much sums up my experience so far:

> Tech giants Google, Microsoft and Facebook are all applying the lessons of machine learning to translation, but a small company called DeepL has outdone them all and raised the bar for the field.
Its translation tool is just as quick as the outsized competition, but more accurate and nuanced than any we’ve tried.

And if it outputs rubbish, I guess I'll be able to adjust that. I'll give the neural nets chapter a try, then :)
