### ISSUE TITLE
translate _chapters_jp/neural_networks.md

### ISSUE THREAD

**Issue by micuat** [ml4a/ml4a.github.io#37]
working on it here:
https://github.com/micuat/ml4a.github.io
http://naotohieda.com/ml4a.github.io/ml4a/jp/neural_networks/

- [x] preface
- [x] Birth and rebirth of neural nets
- [x] From linear classifiers to neurons
- [x] Activation function
- [x] Layers
- [x] Regression
- [x] More layers, more expressiveness
- [x] Classification
- [x] Classification of handwritten digits
- [x] Further reading
- [x] Next Chapter

**Comment by genekogan** [comment]
凄い !

**Comment by micuat** [comment]
@genekogan @kynd how can we translate the demo script?
https://github.com/ml4a/ml4a.github.io/blob/master/demos/demos/simple_forward_pass.js

It will be great if the texts are loaded from asset files instead of hardcoding and an asset file will be loaded according to the language preset (I know it's easy to propose but needs effort to implement it!)

**Comment by micuat** [comment]
@kynd I finished draft of chapter 2. could you take a look when you have time?

**Comment by genekogan** [comment]
@micuat yeah this would be a great idea ... i think the right way to do this would be through putting it as variables in https://raw.githubusercontent.com/ml4a/ml4a.github.io/master/_demos/simple_forward_pass.md and loading from there. i can take a look at this at some point, maybe not this week though.
