### ISSUE TITLE
No issue but does any one know if any east coast companies/startups are doing ML/Art?

### ISSUE THREAD

**Issue by lukeqc825** [ml4a/ml4a.github.io#48]
I am a 28 years old artist, self taught myself ML for a year made a lot of progress, but then I got stuck. I decided this is my passion so I went back to school to study CS in a more formal way. I am about to finish my first year in college and I don't feel like I am being challenged so I am looking for internship opportunities. The problem is I don't know if any well known companies or start ups are doing 2d/3d animation + Machine Learning/Deep Learning on the east coast. Quick google search shows none. I know this is probably not the kind of post I should make for issues but I would like to try my luck. Does any one know any ML/Art internship opportunities?

**Comment by genekogan** [comment]
This issue tracker is to keep track of website development. This post would be better on the [Slack](https://ml-4a.slack.com).
