### ISSUE TITLE
neural nets chapter needs regression example

### ISSUE THREAD

**Issue by genekogan** [ml4a/ml4a.github.io#6]
the section in [the neural nets chapter](http://ml4a.github.io/ml4a/neural_networks/) which says "Random set of dat, 3 cols. 1 regression value" needs a good example.

this would just describe what regression is and how it works. no code included -- it would not need to say much about how the solution is found (except maybe to link to the "training neural nets" chapter). it's a "magic trick" that shows what happens if a neural net has the correct weights for regression.

this leads into the classification example which is more complete already.

**Comment by genekogan** [comment]
awesome!

**Comment by frnsys** [comment]
let me know if it's what you had in mind!
